### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by jackjasper** [MassRobotics-AMR/AMR_Interop_Standard#5]
Is the "sixty (30) seconds" part a typo in the screenshot?  Shouldn't it be "sixty (60) seconds"?

![Typo-section-5-4](https://user-images.githubusercontent.com/29242801/119412633-34c1ff00-bcba-11eb-849e-70335a0a9524.jpg)

This is in the PDF (https://github.com/MassRobotics-AMR/AMR_Interop_Standard/blob/main/AMR_Interop_Standard.pdf)

**Comment by zac-dydek** [comment]
@jackjasper yes, good catch.  I've made the correction in our working document.
